site_name: Symbiotic Programming Index (SPI) Lab Notebook
site_description: Open lab notebook for measuring human–AI coding workflows
site_author: Charles Li
site_url: https://AIPaPaCha.github.io/symbiotic-programming-index
repo_url: https://github.com/AIPaPaCha/symbiotic-programming-index
repo_name: AIPaPaCha/symbiotic-programming-index


theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - toc.follow
    - search.suggest
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - tables
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.tasklist
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search

nav:
  - Home: index.md
  - Dimensions:
      - Code Quality (Qc): qc/index.md
      - Human-off Ratio (HoR): hor/index.md
      - AI Explainability (Exp): exp/index.md
      - Stability (Stb): stb/index.md
      - Natural Language Engagement (NLE): nle/index.md
  - Studies:
      - On Code Quality (Qc) as the Foundational Interface: qc/studies/qc_foundational_interface.md
  - Licenses:
      - License: license.md
